name: Update Repository

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write
  pull-requests: write

on:
  push:
    branches: [ main ]
    paths:
      - 'packages/**'
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    
    steps:
    - uses: actions/checkout@v2
      with:
        path: repo
    
    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm git base-devel
    
    - name: Setup repository structure
      run: |
        mkdir -p repo/docs/x86_64
        mkdir -p repo/packages
    
    - name: Build packages
      working-directory: repo
      run: |
        chmod +x build_repo.sh update_repo.sh
        ./update_repo.sh
    
    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./repo/docs
        publish_branch: gh-pages
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: repo/docs/*.pkg.tar.zst
        name: "Repository Update ${{ github.sha }}"
        tag_name: "repo-${{ github.sha }}"
        body_path: repo/docs/release_notes.md
